import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Chapter 1: Introduction',
      items: ['chapter-1/index', 'chapter-1/topic-1', 'chapter-1/topic-2', 'chapter-1/topic-3', 'chapter-1/topic-4'],
    },
    {
      type: 'category',
      label: 'Chapter 2: Getting Started',
      items: ['chapter-2/index', 'chapter-2/topic-1', 'chapter-2/topic-2', 'chapter-2/topic-3', 'chapter-2/topic-4'],
    },
    {
      type: 'category',
      label: 'Chapter 3: Advanced Topics',
      items: ['chapter-3/index',],
    },
    {
      type: 'category',
      label: 'Chapter 4: Conclusion',
      items: ['chapter-4/index',],
    },
  ],
};

export default sidebars;
